security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin
    role: EXAMPLE
jwt:
  header: Authorization
  secret: my-very-secret-key
spring:
  datasource:
    url: jdbc:mysql://azuredbmysqlsd.mysql.database.azure.com:3306/my-app?useSSL=true&requireSSL=FALSE
    username: ${JDBC_DATABASE_USERNAME:adminazure@azuredbmysqlsd}
    password: ${JDBC_DATABASE_PASSWORD:#Tusasimo12}
    
    dbcp2:
      max-wait-millis: 30000
      validation-query: SELECT 1
      validation-query-timeout: 30
  rabbitmq:
    addresses: amqps://lyervwfn:ndeU5hbnrXjVek2TTqksZgrl77wts2xg@porpoise.rmq.cloudamqp.com/lyervwfn
    username: lyervwfn
    virtual-host: lyervwfn
    host: porpoise-01.rmq.cloudamqp.com
    password: ndeU5hbnrXjVek2TTqksZgrl77wts2xg
    port: 5672
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
        ddl-auto: create/validate/update
    database-platform: org.hibernate.dialect.MySQL8Dialect
